services:
  frontend:
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_SOLANA_NETWORK=devnet
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/wishdb
      - PORT=3001
      - JWT_SECRET=your-secret-key-here
      - ADMIN_WALLETS=wallet1,wallet2
      - OPENROUTER_API_KEY=your-openrouter-key
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./express:/app:delegated
      - backend_node_modules:/app/node_modules
      - ./express/logs:/app/logs

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped
    command: ["--bind_ip", "0.0.0.0"]

volumes:
  mongodb_data:
  backend_node_modules:

networks:
  app-network:
    driver: bridge
