apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: wish-app-prod

commonLabels:
  environment: prod

patches:
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: production
      - op: add
        path: /data/ENABLE_CACHE
        value: "true"
  
  - target:
      kind: ConfigMap
      name: frontend-config
    patch: |-
      - op: replace
        path: /data/VITE_DEBUG_MODE
        value: "false"
      - op: replace
        path: /data/VITE_LOG_LEVEL
        value: "error"

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 400m

  - target:
      kind: PersistentVolumeClaim
      name: mongodb-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi

  - target:
      kind: PersistentVolumeClaim
      name: redis-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi

  - target:
      kind: Ingress
      name: frontend-ingress
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
