---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: wish-app
data:
  NODE_ENV: "production"
  PORT: "3001"
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: "27017"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: wish-app
type: Opaque
data:
  # Acestea sunt doar exemple, în producție trebuie înlocuite cu valori reale encodate base64
  JWT_SECRET: "c2VjcmV0LWtleQ==" # "secret-key" în base64
  MONGODB_USER: "YWRtaW4=" # "admin" în base64
  MONGODB_PASSWORD: "cGFzc3dvcmQ=" # "password" în base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wish-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: my-first-project-backend:latest
          imagePullPolicy: Never # Pentru imagini locale
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wish-app
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: backend
