---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: wish-app
data:
  VITE_API_URL: "http://backend:3001"
  VITE_SOLANA_NETWORK: "devnet"
  VITE_SOLANA_RPC_URL: "https://api.devnet.solana.com"
  VITE_APP_NAME: "Make-A-Wish Game"
  VITE_DEFAULT_CREDITS: "100"
  VITE_WISH_COST: "10"
  VITE_ENABLE_ADMIN_DASHBOARD: "true"
  VITE_ENABLE_SYSTEM_MONITORING: "true"
  VITE_DEBUG_MODE: "false"
  VITE_LOG_LEVEL: "info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wish-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: my-first-project-frontend:latest
          imagePullPolicy: Never # Pentru imagini locale
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wish-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: wish-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
