apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongodb.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml

commonLabels:
  app.kubernetes.io/name: wish-app
  app.kubernetes.io/part-of: wish-platform

namespace: wish-app
